-- SumanTV Shorts — Phase 1 data foundation
-- This migration is intentionally additive because the Supabase project is shared
-- with other SumanTV applications. Every new public object is prefixed with shorts_.

begin;

create schema if not exists shorts_private;

revoke all on schema shorts_private from public, anon;
grant usage on schema shorts_private to authenticated, service_role;

create or replace function shorts_private.is_editor()
returns boolean
language sql
stable
security invoker
set search_path = ''
as $$
  select coalesce(
    (select auth.jwt()) -> 'app_metadata' ->> 'shorts_role',
    ''
  ) in ('editor', 'admin');
$$;

revoke all on function shorts_private.is_editor() from public, anon;
grant execute on function shorts_private.is_editor() to authenticated, service_role;

create or replace function shorts_private.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = pg_catalog.now();
  return new;
end;
$$;

revoke all on function shorts_private.set_updated_at() from public, anon, authenticated;

create table public.shorts_categories (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name_te text not null,
  name_en text not null,
  color text not null default '#f4c94d',
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint shorts_categories_slug_format
    check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  constraint shorts_categories_color_format
    check (color ~ '^#[0-9A-Fa-f]{6}$'),
  constraint shorts_categories_names_not_blank
    check (btrim(name_te) <> '' and btrim(name_en) <> '')
);

create table public.shorts_stories (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  category_id bigint not null
    references public.shorts_categories(id)
    on update cascade
    on delete restrict,
  title_te text not null,
  title_en text,
  summary_te text not null,
  summary_en text,
  source_name text not null,
  source_url text,
  image_url text,
  image_alt_te text,
  status text not null default 'draft',
  is_breaking boolean not null default false,
  is_live boolean not null default false,
  published_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint shorts_stories_slug_format
    check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  constraint shorts_stories_status
    check (status in ('draft', 'review', 'published', 'archived')),
  constraint shorts_stories_required_text
    check (
      btrim(title_te) <> ''
      and btrim(summary_te) <> ''
      and btrim(source_name) <> ''
    ),
  constraint shorts_stories_source_url_https
    check (source_url is null or source_url ~ '^https://'),
  constraint shorts_stories_image_url_https
    check (image_url is null or image_url ~ '^https://'),
  constraint shorts_stories_publish_timestamp
    check (status <> 'published' or published_at is not null),
  constraint shorts_stories_live_requires_publish
    check (not is_live or status = 'published')
);

create table public.shorts_deals (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title_te text not null,
  description_te text not null,
  current_price numeric(12, 2),
  original_price numeric(12, 2),
  currency text not null default 'INR',
  image_url text,
  destination_url text,
  sponsor_name text,
  sponsorship_disclosure text,
  status text not null default 'draft',
  starts_at timestamptz,
  expires_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint shorts_deals_slug_format
    check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  constraint shorts_deals_status
    check (status in ('draft', 'review', 'published', 'archived')),
  constraint shorts_deals_required_text
    check (btrim(title_te) <> '' and btrim(description_te) <> ''),
  constraint shorts_deals_currency_format
    check (currency ~ '^[A-Z]{3}$'),
  constraint shorts_deals_prices_nonnegative
    check (
      (current_price is null or current_price >= 0)
      and (original_price is null or original_price >= 0)
    ),
  constraint shorts_deals_image_url_https
    check (image_url is null or image_url ~ '^https://'),
  constraint shorts_deals_destination_url_https
    check (destination_url is null or destination_url ~ '^https://'),
  constraint shorts_deals_sponsorship_label
    check (
      sponsor_name is null
      or (
        btrim(sponsor_name) <> ''
        and sponsorship_disclosure is not null
        and btrim(sponsorship_disclosure) <> ''
      )
    ),
  constraint shorts_deals_valid_window
    check (expires_at is null or starts_at is null or expires_at > starts_at),
  constraint shorts_deals_publish_timestamp
    check (status <> 'published' or starts_at is not null)
);

create table public.shorts_leads (
  id bigint generated by default as identity primary key,
  deal_id bigint not null
    references public.shorts_deals(id)
    on update cascade
    on delete restrict,
  full_name text not null,
  phone_e164 text not null,
  city text,
  consent boolean not null,
  consent_text_version text not null,
  source_page text not null default 'shorts-web',
  status text not null default 'new',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint shorts_leads_required_name
    check (btrim(full_name) <> ''),
  constraint shorts_leads_phone_e164
    check (phone_e164 ~ '^\+[1-9][0-9]{7,14}$'),
  constraint shorts_leads_consent_required
    check (consent),
  constraint shorts_leads_status
    check (status in ('new', 'contacted', 'qualified', 'closed', 'deleted'))
);

create table public.shorts_story_reactions (
  user_id uuid not null default auth.uid()
    references auth.users(id)
    on delete cascade,
  story_id bigint not null
    references public.shorts_stories(id)
    on update cascade
    on delete cascade,
  reaction_type text not null default 'like',
  created_at timestamptz not null default now(),
  primary key (user_id, story_id, reaction_type),
  constraint shorts_story_reactions_type
    check (reaction_type in ('like'))
);

create table public.shorts_saved_stories (
  user_id uuid not null default auth.uid()
    references auth.users(id)
    on delete cascade,
  story_id bigint not null
    references public.shorts_stories(id)
    on update cascade
    on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, story_id)
);

create index shorts_stories_public_feed_idx
  on public.shorts_stories (is_breaking desc, published_at desc, id desc)
  where status = 'published';

create index shorts_stories_category_feed_idx
  on public.shorts_stories (category_id, published_at desc, id desc)
  where status = 'published';

create index shorts_stories_created_by_idx
  on public.shorts_stories (created_by)
  where created_by is not null;

create index shorts_stories_updated_by_idx
  on public.shorts_stories (updated_by)
  where updated_by is not null;

create index shorts_deals_public_feed_idx
  on public.shorts_deals (starts_at desc, id desc)
  where status = 'published';

create index shorts_deals_created_by_idx
  on public.shorts_deals (created_by)
  where created_by is not null;

create index shorts_leads_deal_created_idx
  on public.shorts_leads (deal_id, created_at desc);

create index shorts_leads_status_created_idx
  on public.shorts_leads (status, created_at desc);

create index shorts_story_reactions_story_idx
  on public.shorts_story_reactions (story_id);

create index shorts_saved_stories_story_idx
  on public.shorts_saved_stories (story_id);

create trigger shorts_categories_set_updated_at
before update on public.shorts_categories
for each row execute function shorts_private.set_updated_at();

create trigger shorts_stories_set_updated_at
before update on public.shorts_stories
for each row execute function shorts_private.set_updated_at();

create trigger shorts_deals_set_updated_at
before update on public.shorts_deals
for each row execute function shorts_private.set_updated_at();

create trigger shorts_leads_set_updated_at
before update on public.shorts_leads
for each row execute function shorts_private.set_updated_at();

alter table public.shorts_categories enable row level security;
alter table public.shorts_stories enable row level security;
alter table public.shorts_deals enable row level security;
alter table public.shorts_leads enable row level security;
alter table public.shorts_story_reactions enable row level security;
alter table public.shorts_saved_stories enable row level security;

create policy "shorts categories public read"
on public.shorts_categories
for select
to anon
using (is_active);

create policy "shorts categories authenticated read"
on public.shorts_categories
for select
to authenticated
using (is_active or (select shorts_private.is_editor()));

create policy "shorts categories editor insert"
on public.shorts_categories
for insert
to authenticated
with check ((select shorts_private.is_editor()));

create policy "shorts categories editor update"
on public.shorts_categories
for update
to authenticated
using ((select shorts_private.is_editor()))
with check ((select shorts_private.is_editor()));

create policy "shorts categories editor delete"
on public.shorts_categories
for delete
to authenticated
using ((select shorts_private.is_editor()));

create policy "shorts stories public read"
on public.shorts_stories
for select
to anon
using (
  status = 'published'
  and published_at <= now()
);

create policy "shorts stories authenticated read"
on public.shorts_stories
for select
to authenticated
using (
  (
    status = 'published'
    and published_at <= now()
  )
  or (select shorts_private.is_editor())
);

create policy "shorts stories editor insert"
on public.shorts_stories
for insert
to authenticated
with check ((select shorts_private.is_editor()));

create policy "shorts stories editor update"
on public.shorts_stories
for update
to authenticated
using ((select shorts_private.is_editor()))
with check ((select shorts_private.is_editor()));

create policy "shorts stories editor delete"
on public.shorts_stories
for delete
to authenticated
using ((select shorts_private.is_editor()));

create policy "shorts deals public read"
on public.shorts_deals
for select
to anon
using (
  status = 'published'
  and starts_at <= now()
  and (expires_at is null or expires_at > now())
);

create policy "shorts deals authenticated read"
on public.shorts_deals
for select
to authenticated
using (
  (
    status = 'published'
    and starts_at <= now()
    and (expires_at is null or expires_at > now())
  )
  or (select shorts_private.is_editor())
);

create policy "shorts deals editor insert"
on public.shorts_deals
for insert
to authenticated
with check ((select shorts_private.is_editor()));

create policy "shorts deals editor update"
on public.shorts_deals
for update
to authenticated
using ((select shorts_private.is_editor()))
with check ((select shorts_private.is_editor()));

create policy "shorts deals editor delete"
on public.shorts_deals
for delete
to authenticated
using ((select shorts_private.is_editor()));

-- Lead PII is intentionally unavailable to browser roles in Phase 1.
-- A later server-side endpoint can validate, rate-limit, and insert with service_role.

create policy "shorts leads browser deny"
on public.shorts_leads
as restrictive
for all
to anon, authenticated
using (false)
with check (false);

create policy "shorts reactions owner read"
on public.shorts_story_reactions
for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "shorts reactions owner insert"
on public.shorts_story_reactions
for insert
to authenticated
with check ((select auth.uid()) = user_id);

create policy "shorts reactions owner delete"
on public.shorts_story_reactions
for delete
to authenticated
using ((select auth.uid()) = user_id);

create policy "shorts saved stories owner read"
on public.shorts_saved_stories
for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "shorts saved stories owner insert"
on public.shorts_saved_stories
for insert
to authenticated
with check ((select auth.uid()) = user_id);

create policy "shorts saved stories owner delete"
on public.shorts_saved_stories
for delete
to authenticated
using ((select auth.uid()) = user_id);

revoke all on table
  public.shorts_categories,
  public.shorts_stories,
  public.shorts_deals,
  public.shorts_leads,
  public.shorts_story_reactions,
  public.shorts_saved_stories
from public, anon, authenticated;

grant select on table
  public.shorts_categories,
  public.shorts_stories,
  public.shorts_deals
to anon, authenticated;

grant insert, update, delete on table
  public.shorts_categories,
  public.shorts_stories,
  public.shorts_deals
to authenticated;

grant select, insert, delete on table
  public.shorts_story_reactions,
  public.shorts_saved_stories
to authenticated;

grant select, insert, update, delete on table
  public.shorts_categories,
  public.shorts_stories,
  public.shorts_deals,
  public.shorts_leads,
  public.shorts_story_reactions,
  public.shorts_saved_stories
to service_role;

grant usage, select on sequence
  public.shorts_categories_id_seq,
  public.shorts_stories_id_seq,
  public.shorts_deals_id_seq
to authenticated, service_role;

grant usage, select on sequence public.shorts_leads_id_seq to service_role;

insert into public.shorts_categories (slug, name_te, name_en, color, sort_order)
values
  ('latest', 'తాజా', 'Latest', '#F4C94D', 10),
  ('andhra-pradesh', 'ఆంధ్రప్రదేశ్', 'Andhra Pradesh', '#47B5FF', 20),
  ('telangana', 'తెలంగాణ', 'Telangana', '#8B7CFF', 30),
  ('india', 'భారతదేశం', 'India', '#FF7B54', 40),
  ('world', 'ప్రపంచం', 'World', '#B983FF', 50),
  ('business', 'బిజినెస్', 'Business', '#4DD4AC', 60),
  ('sports', 'క్రీడలు', 'Sports', '#FF6B6B', 70),
  ('entertainment', 'వినోదం', 'Entertainment', '#FF77A8', 80),
  ('health', 'ఆరోగ్యం', 'Health', '#51D88A', 90),
  ('technology', 'టెక్నాలజీ', 'Technology', '#5AA9FF', 100)
on conflict (slug) do update
set
  name_te = excluded.name_te,
  name_en = excluded.name_en,
  color = excluded.color,
  sort_order = excluded.sort_order,
  is_active = true;

insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'shorts-news-images',
  'shorts-news-images',
  true,
  5242880,
  array['image/jpeg', 'image/png', 'image/webp', 'image/avif']
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create policy "shorts news images editor insert"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'shorts-news-images'
  and (select shorts_private.is_editor())
);

create policy "shorts news images editor update"
on storage.objects
for update
to authenticated
using (
  bucket_id = 'shorts-news-images'
  and (select shorts_private.is_editor())
)
with check (
  bucket_id = 'shorts-news-images'
  and (select shorts_private.is_editor())
);

create policy "shorts news images editor delete"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'shorts-news-images'
  and (select shorts_private.is_editor())
);

comment on table public.shorts_stories is
  'Verified SumanTV Shorts editorial stories. Browser reads are limited to published rows by RLS.';

comment on table public.shorts_leads is
  'Private deal-interest PII. No anon or authenticated Data API grants in Phase 1.';

comment on column public.shorts_stories.is_live is
  'Editorial live flag. The client additionally expires this label after six hours.';

commit;
