-- SumanTV Shorts — Phase 3A multimedia publishing
-- Adds galleries and YouTube formats without changing existing article rows.

begin;

alter table public.shorts_stories
  add column if not exists content_type text not null default 'article',
  add column if not exists youtube_video_id text;

alter table public.shorts_stories
  add constraint shorts_stories_content_type
    check (content_type in ('article', 'gallery', 'youtube_short', 'youtube_video')),
  add constraint shorts_stories_youtube_video_id
    check (
      (
        content_type in ('youtube_short', 'youtube_video')
        and youtube_video_id ~ '^[A-Za-z0-9_-]{11}$'
      )
      or (
        content_type in ('article', 'gallery')
        and youtube_video_id is null
      )
    );

create table public.shorts_story_media (
  id bigint generated by default as identity primary key,
  story_id bigint not null
    references public.shorts_stories(id)
    on update cascade
    on delete cascade,
  position smallint not null,
  image_url text not null,
  image_alt_te text,
  caption_te text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint shorts_story_media_position
    check (position between 1 and 10),
  constraint shorts_story_media_image_url_https
    check (image_url ~ '^https://'),
  constraint shorts_story_media_text
    check (
      (image_alt_te is null or btrim(image_alt_te) <> '')
      and (caption_te is null or btrim(caption_te) <> '')
    ),
  constraint shorts_story_media_story_position_unique
    unique (story_id, position)
);

create index shorts_story_media_story_idx
  on public.shorts_story_media (story_id, position);

create trigger shorts_story_media_set_updated_at
before update on public.shorts_story_media
for each row execute function shorts_private.set_updated_at();

alter table public.shorts_story_media enable row level security;

create policy "shorts story media public read"
on public.shorts_story_media
for select
to anon
using (
  exists (
    select 1
    from public.shorts_stories story
    where story.id = shorts_story_media.story_id
      and story.status = 'published'
      and story.published_at <= now()
  )
);

create policy "shorts story media authenticated read"
on public.shorts_story_media
for select
to authenticated
using (
  (select shorts_private.is_editor())
  or exists (
    select 1
    from public.shorts_stories story
    where story.id = shorts_story_media.story_id
      and story.status = 'published'
      and story.published_at <= now()
  )
);

create policy "shorts story media editorial insert"
on public.shorts_story_media
for insert
to authenticated
with check (
  exists (
    select 1
    from public.shorts_stories story
    where story.id = shorts_story_media.story_id
      and (
        (select shorts_private.is_admin())
        or (
          (select shorts_private.is_editor())
          and story.status in ('draft', 'review')
        )
      )
  )
);

create policy "shorts story media editorial update"
on public.shorts_story_media
for update
to authenticated
using (
  exists (
    select 1
    from public.shorts_stories story
    where story.id = shorts_story_media.story_id
      and (
        (select shorts_private.is_admin())
        or (
          (select shorts_private.is_editor())
          and story.status in ('draft', 'review')
        )
      )
  )
)
with check (
  exists (
    select 1
    from public.shorts_stories story
    where story.id = shorts_story_media.story_id
      and (
        (select shorts_private.is_admin())
        or (
          (select shorts_private.is_editor())
          and story.status in ('draft', 'review')
        )
      )
  )
);

create policy "shorts story media editorial delete"
on public.shorts_story_media
for delete
to authenticated
using (
  exists (
    select 1
    from public.shorts_stories story
    where story.id = shorts_story_media.story_id
      and (
        (select shorts_private.is_admin())
        or (
          (select shorts_private.is_editor())
          and story.status in ('draft', 'review')
        )
      )
  )
);

revoke all on table public.shorts_story_media from public, anon, authenticated;
grant select on table public.shorts_story_media to anon, authenticated;
grant insert, update, delete on table public.shorts_story_media to authenticated;
grant select, insert, update, delete on table public.shorts_story_media to service_role;
grant usage, select on sequence public.shorts_story_media_id_seq to authenticated, service_role;

insert into public.shorts_categories (slug, name_te, name_en, color, sort_order)
values
  ('movies', 'సినిమాలు', 'Movies', '#FF8A65', 81),
  ('celebrities', 'సెలబ్రిటీలు', 'Celebrities', '#EC70A6', 82)
on conflict (slug) do update
set
  name_te = excluded.name_te,
  name_en = excluded.name_en,
  color = excluded.color,
  sort_order = excluded.sort_order,
  is_active = true;

comment on column public.shorts_stories.content_type is
  'Public presentation type: article, gallery, youtube_short, or youtube_video.';

comment on column public.shorts_stories.youtube_video_id is
  'Validated 11-character YouTube video ID; raw embed HTML is never stored.';

comment on table public.shorts_story_media is
  'Ordered, rights-cleared gallery images associated with a SumanTV Shorts story.';

commit;
