-- SumanTV Shorts — Phase 3B first-party analytics
-- Stores one privacy-safe event per story, browser-tab session and event type.

begin;

create table public.shorts_story_events (
  id bigint generated by default as identity primary key,
  story_id bigint not null
    references public.shorts_stories(id)
    on update cascade
    on delete cascade,
  session_id uuid not null,
  event_type text not null,
  created_at timestamptz not null default now(),
  constraint shorts_story_events_type
    check (
      event_type in (
        'view',
        'complete',
        'like',
        'save',
        'share',
        'video_play',
        'gallery_swipe'
      )
    ),
  constraint shorts_story_events_session_event_unique
    unique (story_id, session_id, event_type)
);

create index shorts_story_events_created_idx
  on public.shorts_story_events (created_at desc);

create index shorts_story_events_story_created_idx
  on public.shorts_story_events (story_id, created_at desc);

alter table public.shorts_story_events enable row level security;

create policy "shorts analytics published story insert"
on public.shorts_story_events
for insert
to anon, authenticated
with check (
  exists (
    select 1
    from public.shorts_stories story
    where story.id = shorts_story_events.story_id
      and story.status = 'published'
      and story.published_at <= now()
  )
);

create policy "shorts analytics admin read"
on public.shorts_story_events
for select
to authenticated
using ((select shorts_private.is_admin()));

revoke all on table public.shorts_story_events from public, anon, authenticated;
grant insert on table public.shorts_story_events to anon, authenticated;
grant select on table public.shorts_story_events to authenticated;
grant select, insert, update, delete on table public.shorts_story_events to service_role;
grant usage, select on sequence public.shorts_story_events_id_seq
  to anon, authenticated, service_role;

create or replace function public.shorts_analytics_dashboard(p_days integer default 7)
returns jsonb
language plpgsql
stable
security invoker
set search_path = ''
as $$
declare
  v_days integer := least(greatest(coalesce(p_days, 7), 1), 90);
  v_start timestamptz;
  v_result jsonb;
begin
  if (select auth.uid()) is null or not (select shorts_private.is_admin()) then
    raise exception 'Admin access required'
      using errcode = '42501';
  end if;

  v_start := date_trunc('day', now()) - ((v_days - 1) * interval '1 day');

  with filtered_events as (
    select event.story_id, event.session_id, event.event_type, event.created_at
    from public.shorts_story_events event
    where event.created_at >= v_start
  ),
  totals as (
    select
      count(*) filter (where event_type = 'view') as views,
      count(distinct session_id) filter (where event_type = 'view') as readers,
      count(*) filter (where event_type = 'complete') as completions,
      count(*) filter (where event_type = 'like') as likes,
      count(*) filter (where event_type = 'save') as saves,
      count(*) filter (where event_type = 'share') as shares,
      count(*) filter (where event_type = 'video_play') as video_plays,
      count(*) filter (where event_type = 'gallery_swipe') as gallery_swipes
    from filtered_events
  ),
  daily as (
    select
      day::date as date,
      count(event.*) filter (where event.event_type = 'view') as views,
      count(distinct event.session_id) filter (where event.event_type = 'view') as readers,
      count(event.*) filter (
        where event.event_type in ('like', 'save', 'share', 'video_play', 'gallery_swipe')
      ) as engagements
    from generate_series(
      date_trunc('day', now()) - ((v_days - 1) * interval '1 day'),
      date_trunc('day', now()),
      interval '1 day'
    ) day
    left join filtered_events event
      on event.created_at >= day
     and event.created_at < day + interval '1 day'
    group by day
    order by day
  ),
  by_content_type as (
    select
      story.content_type as label,
      count(event.*) filter (where event.event_type = 'view') as views,
      count(event.*) filter (
        where event.event_type in ('like', 'save', 'share', 'video_play', 'gallery_swipe')
      ) as engagements
    from public.shorts_stories story
    left join filtered_events event on event.story_id = story.id
    where story.status = 'published'
    group by story.content_type
    order by views desc, story.content_type
  ),
  by_category as (
    select
      category.name_te as label,
      count(event.*) filter (where event.event_type = 'view') as views,
      count(event.*) filter (
        where event.event_type in ('like', 'save', 'share', 'video_play', 'gallery_swipe')
      ) as engagements
    from public.shorts_categories category
    join public.shorts_stories story on story.category_id = category.id
    left join filtered_events event on event.story_id = story.id
    where story.status = 'published'
    group by category.id, category.name_te
    order by views desc, category.name_te
  ),
  top_stories as (
    select
      story.id,
      story.slug,
      story.title_te as title,
      story.content_type,
      count(event.*) filter (where event.event_type = 'view') as views,
      count(event.*) filter (where event.event_type = 'complete') as completions,
      count(event.*) filter (where event.event_type = 'like') as likes,
      count(event.*) filter (where event.event_type = 'save') as saves,
      count(event.*) filter (where event.event_type = 'share') as shares,
      count(event.*) filter (where event.event_type = 'video_play') as video_plays,
      count(event.*) filter (where event.event_type = 'gallery_swipe') as gallery_swipes
    from public.shorts_stories story
    left join filtered_events event on event.story_id = story.id
    where story.status = 'published'
    group by story.id
    order by views desc, story.published_at desc
    limit 20
  )
  select jsonb_build_object(
    'rangeDays', v_days,
    'generatedAt', now(),
    'summary', (
      select jsonb_build_object(
        'views', views,
        'readers', readers,
        'completions', completions,
        'likes', likes,
        'saves', saves,
        'shares', shares,
        'videoPlays', video_plays,
        'gallerySwipes', gallery_swipes,
        'completionRate', coalesce(round(100.0 * completions / nullif(views, 0), 1), 0),
        'engagementRate', coalesce(round(
          100.0 * (likes + saves + shares + video_plays + gallery_swipes) / nullif(views, 0),
          1
        ), 0)
      )
      from totals
    ),
    'daily', (
      select coalesce(jsonb_agg(jsonb_build_object(
        'date', date,
        'views', views,
        'readers', readers,
        'engagements', engagements
      ) order by date), '[]'::jsonb)
      from daily
    ),
    'contentTypes', (
      select coalesce(jsonb_agg(jsonb_build_object(
        'label', label,
        'views', views,
        'engagements', engagements
      ) order by views desc, label), '[]'::jsonb)
      from by_content_type
    ),
    'categories', (
      select coalesce(jsonb_agg(jsonb_build_object(
        'label', label,
        'views', views,
        'engagements', engagements
      ) order by views desc, label), '[]'::jsonb)
      from by_category
    ),
    'topStories', (
      select coalesce(jsonb_agg(jsonb_build_object(
        'id', id,
        'slug', slug,
        'title', title,
        'contentType', content_type,
        'views', views,
        'completions', completions,
        'likes', likes,
        'saves', saves,
        'shares', shares,
        'videoPlays', video_plays,
        'gallerySwipes', gallery_swipes,
        'completionRate', coalesce(round(100.0 * completions / nullif(views, 0), 1), 0)
      ) order by views desc, id desc), '[]'::jsonb)
      from top_stories
    )
  )
  into v_result;

  return v_result;
end;
$$;

revoke all on function public.shorts_analytics_dashboard(integer)
  from public, anon, authenticated;
grant execute on function public.shorts_analytics_dashboard(integer)
  to authenticated, service_role;

comment on table public.shorts_story_events is
  'Privacy-safe first-party engagement events. No IP, email, user-agent or fingerprint data.';

comment on column public.shorts_story_events.session_id is
  'Random browser-tab session UUID used only to deduplicate each event type per story.';

comment on function public.shorts_analytics_dashboard(integer) is
  'Admin-only aggregate analytics for the SumanTV Shorts editorial dashboard.';

commit;
